<?php

namespace App\Http\Controllers;

use App\Models\PaymentTransaction;
use App\Support\Payments\PaymentService;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Log;

/**
 * The platform-wide Paystack webhook endpoint. Signature verification is
 * the only thing that authenticates a request here — there is no session,
 * and nothing in the payload itself is trusted until the signature check
 * passes and the referenced transaction is independently re-verified with
 * Paystack's own API (see PaymentService::verifyAndActivate()).
 */
class PaystackWebhookController extends Controller
{
    public function __construct(private readonly PaymentService $payments) {}

    public function handle(Request $request): Response
    {
        if (! $this->hasValidSignature($request)) {
            Log::warning('paystack.webhook.invalid_signature');

            return response('', 401);
        }

        $payload = json_decode($request->getContent(), true);

        if (! is_array($payload) || ! isset($payload['event'])) {
            Log::warning('paystack.webhook.malformed_payload');

            return response('', 400);
        }

        // Only successful charges can ever activate a subscription; every
        // other event type is acknowledged and ignored.
        if ($payload['event'] !== 'charge.success') {
            return response('', 200);
        }

        $reference = (string) ($payload['data']['reference'] ?? '');

        if ($reference === '') {
            Log::warning('paystack.webhook.missing_reference');

            return response('', 200);
        }

        $transaction = PaymentTransaction::where('reference', $reference)->first();

        if (! $transaction) {
            // An unknown reference isn't this application's error to
            // surface to Paystack — acknowledge and move on.
            Log::info('paystack.webhook.unknown_reference');

            return response('', 200);
        }

        // No $expectedBusiness restriction here: the reference itself
        // (generated by this app, looked up by unique key) is what
        // determines which business this payment belongs to — nothing
        // about "who's asking" applies to a server-to-server webhook.
        $this->payments->verifyAndActivate($transaction);

        return response('', 200);
    }

    /**
     * Validates the x-paystack-signature header: HMAC-SHA512 of the raw
     * request body, using the configured secret key, compared with
     * hash_equals to avoid a timing side-channel.
     */
    private function hasValidSignature(Request $request): bool
    {
        $secret = config('services.paystack.secret_key');

        if (! is_string($secret) || $secret === '') {
            return false;
        }

        $signature = (string) $request->header('x-paystack-signature', '');

        if ($signature === '') {
            return false;
        }

        $expected = hash_hmac('sha512', $request->getContent(), $secret);

        return hash_equals($expected, $signature);
    }
}
